# Generated by Django 6.1.1 on 2026-09-21 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_financial_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialinquirysession',
            name='is_active',
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_session', to=settings.AUTH_USER_MODEL),
        ),
    ]
