# Generated by Django 6.1.1 on 2026-09-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_financialinquirysession_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinquirysession',
            name='extra_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='has_extra_income',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
