# Generated by Django 6.1.1 on 2026-09-21 08:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_financialinquirysession_extra_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinquirysession',
            name='expense_clothing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='expense_entertainment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='expense_market',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='expense_online_shopping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='expense_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='expense_restaurant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='expense_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='expense_utilities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='financial_assessment',
            field=models.CharField(blank=True, choices=[('good_manager', 'Pulumu yaxşı idarə edə bilirəm'), ('sometimes_breaks_plan', 'Bəzən planı poza bilirəm'), ('nothing_left', 'Ay sonuna pul qalmır')], max_length=30),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='has_credit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='housing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('Özümündür', 'Özümündür'), ('Kirayədir', 'Kirayədir'), ('İpotekadır', 'İpotekadır')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='recurring_clothing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='recurring_entertainment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='recurring_market',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='recurring_online_shopping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='recurring_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='recurring_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='recurring_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='recurring_utilities',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('months', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='users.financialinquirysession')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.CharField(choices=[('travel', 'travel'), ('home', 'home'), ('car', 'car'), ('education', 'education'), ('wedding', 'wedding'), ('business', 'business'), ('emergency', 'emergency'), ('other', 'other')], max_length=50)),
                ('custom_name', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('Aşağı prioritet', 'Aşağı prioritet'), ('Orta prioritet', 'Orta prioritet'), ('Yuxarı prioritet', 'Yuxarı prioritet')], default='Orta prioritet', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='users.financialinquirysession')),
            ],
            options={
                'unique_together': {('session', 'goal_id')},
            },
        ),
    ]
