# Generated by Django 6.1.1 on 2026-09-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_financialinquirysession_expense_clothing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinquirysession',
            name='monthly_savings_ability',
            field=models.CharField(blank=True, choices=[('can_save', 'Bacarıram'), ('sometimes', 'Bəzən'), ('cannot_save', 'Xeyr')], default='sometimes', max_length=20),
        ),
    ]
