# Generated by Django 6.1.1 on 2026-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_financialinquirysession_monthly_savings_ability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savingsgoal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='financialinquirysession',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='annual_budget_priority',
            field=models.CharField(blank=True, choices=[('savings', 'Yığımları artırmaq'), ('debt_repayment', 'Borcları daha sürətli bağlamaq'), ('balance', 'Balanslı yaşamaq (yığım + əyləncə)'), ('investment', 'Gələcəyə yatırım etmək')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='expense_clothing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='expense_entertainment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='expense_market',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='expense_online_shopping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='expense_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='expense_restaurant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='expense_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='expense_utilities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='financial_assessment',
            field=models.CharField(blank=True, choices=[('good_manager', 'Pulumu yaxşı idarə edə bilirəm'), ('sometimes_breaks_plan', 'Bəzən planı poza bilirəm'), ('nothing_left', 'Ay sonuna pul qalmır')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('Özümündür', 'Özümündür'), ('Kirayədir', 'Kirayədir'), ('İpotekadır', 'İpotekadır')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financialinquirysession',
            name='monthly_savings_ability',
            field=models.CharField(blank=True, choices=[('can_save', 'Bəli, müntəzəm'), ('sometimes', 'Bəzən'), ('cannot_save', 'Xeyr')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='goal_id',
            field=models.CharField(choices=[('emergency', 'Təcili vəziyyətlər fondu'), ('travel', 'Səyahət / Tətil'), ('home', 'Ev / Mənzil almaq'), ('car', 'Avtomobil almaq'), ('education', 'Təhsil / İnkişaf'), ('other', 'Digər')], max_length=50),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='priority',
            field=models.CharField(choices=[('Yüksək prioritet', 'Yüksək prioritet'), ('Orta prioritet', 'Orta prioritet'), ('Aşağı prioritet', 'Aşağı prioritet')], default='Orta prioritet', max_length=50),
        ),
    ]
