# Generated by Django 6.1.1 on 2026-09-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_savingsgoal_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='goal_id',
            field=models.CharField(choices=[('emergency', 'Təcili vəziyyətlər fondu'), ('travel', 'Səyahət / Tətil'), ('home', 'Ev / Mənzil almaq'), ('car', 'Avtomobil almaq'), ('education', 'Təhsil / İnkişaf'), ('business', 'Biznes qurmaq'), ('wedding', 'Toy üçün'), ('other', 'Digər')], max_length=50),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='priority',
            field=models.CharField(choices=[('Yuxarı prioritet', 'Yüksək prioritet'), ('Orta prioritet', 'Orta prioritet'), ('Aşağı prioritet', 'Aşağı prioritet')], default='Orta prioritet', max_length=50),
        ),
    ]
