# Generated by Django 6.1.1 on 2026-09-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_savingsgoal_goal_id_alter_savingsgoal_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinquirysession',
            name='annual_budget_priority',
            field=models.CharField(blank=True, choices=[('Daha çox qənaət etmək', 'Daha çox qənaət etmək'), ('Xərclərə nəzarət etmək', 'Xərclərə nəzarət etmək'), ('Borcları azaltmaq', 'Borcları azaltmaq'), ('Gəliri daha düzgün bölüşdürmək', 'Gəliri daha düzgün bölüşdürmək'), ('Gözlənilməz xərclərə hazır olmaq', 'Gözlənilməz xərclərə hazır olmaq'), ('Gələcək üçün pul toplamaq', 'Gələcək üçün pul toplamaq')], max_length=50, null=True),
        ),
    ]
