# Generated by Django 6.1.1 on 2026-09-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_financialinquirysession_annual_budget_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinquirysession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
