# Generated by Django 6.1.1 on 2026-09-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_financialinquirysession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinquirysession',
            name='ai_response_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='annual_totals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='budget_comparison',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='financial_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='financial_status_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='monthly_table',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='recommended_annual_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='recommended_monthly_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialinquirysession',
            name='savings_goals_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
