# Generated by Django 6.1.1 on 2026-09-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_financialinquirysession_ai_response_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='priority',
            field=models.CharField(choices=[('Yuxarı prioritet', 'Yüksək'), ('Orta prioritet', 'Orta'), ('Aşağı prioritet', 'Aşağı')], default='Orta prioritet', max_length=50),
        ),
    ]
