# Generated by Django 5.2.17 on 2026-10-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_savingsgoal_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialinquirysession",
            name="plan_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="financialinquirysession",
            name="plan_text_source",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="financialinquirysession",
            name="plan_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="financialinquirysession",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
