# Generated by Django 5.2.17 on 2026-10-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_plan_status_and_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialinquirysession",
            name="plan_adjustments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
