# Generated by Django 5.2.17 on 2026-10-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_plan_adjustments"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialinquirysession",
            name="plan_variant",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
