# Generated by Django 5.2.17 on 2026-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_plan_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingsgoal",
            name="deadline_months",
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="saved_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
